
import numpy as np
import pandas as pd


class RiskMetrics:
    """
    Calculates risk-related backtest metrics.

    Current implementation works with the equity curve
    generated by ReturnMetrics.

    Equity uses realized completed-trade P&L, which includes
    quantity, but does not mark open positions to market.
    """

    # ==================================================
    # MAXIMUM DRAWDOWN
    # ==================================================

    @staticmethod
    def max_drawdown(
        equity: pd.DataFrame
    ) -> float:
        """
        Calculate maximum drawdown in currency units.

        Drawdown =
            Equity - Previous Peak

        Maximum Drawdown is the largest negative
        drawdown observed.

        Returns
        -------
        float
            Maximum drawdown as a positive number.
        """

        if equity.empty:
            return 0.0

        if "equity" not in equity.columns:
            raise ValueError(
                "Equity DataFrame must contain an "
                "'equity' column."
            )

        equity_values = (
            pd.to_numeric(
                equity["equity"],
                errors="coerce"
            )
            .dropna()
        )

        if equity_values.empty:
            return 0.0

        running_peak = equity_values.cummax()

        drawdown = (
            equity_values - running_peak
        )

        # Convert to positive drawdown amount.
        max_drawdown = abs(
            drawdown.min()
        )

        return float(max_drawdown)

    # ==================================================
    # MAXIMUM DRAWDOWN %
    # ==================================================

    @staticmethod
    def max_drawdown_percent(
        equity: pd.DataFrame
    ) -> float:
        """
        Calculate maximum drawdown as a percentage.

        Drawdown % =
            (Equity - Peak Equity) / Peak Equity * 100

        Returns
        -------
        float
            Maximum drawdown percentage as a positive number.
        """

        if equity.empty:
            return 0.0

        if "equity" not in equity.columns:
            raise ValueError(
                "Equity DataFrame must contain an "
                "'equity' column."
            )

        equity_values = (
            pd.to_numeric(
                equity["equity"],
                errors="coerce"
            )
            .dropna()
        )

        if equity_values.empty:
            return 0.0

        running_peak = equity_values.cummax()

        drawdown_percent = (
            (
                equity_values
                - running_peak
            )
            / running_peak
        ) * 100

        return float(
            abs(drawdown_percent.min())
        )

    # ==================================================
    # SHARPE RATIO
    # ==================================================

    @staticmethod
    def sharpe_ratio(
        trades: pd.DataFrame,
        capital: float
    ) -> float:
        """
        Calculate a simplified trade-level Sharpe Ratio.

        This uses trade P&L relative to initial capital
        as the return series.

        This is NOT a true daily portfolio Sharpe Ratio.

        A proper portfolio Sharpe Ratio should eventually
        be calculated from daily portfolio returns.
        """

        if trades.empty:
            return 0.0

        if capital <= 0:
            raise ValueError(
                "Capital must be greater than 0."
            )

        if "pnl" not in trades.columns:
            raise ValueError(
                "Trades DataFrame must contain "
                "a 'pnl' column."
            )

        returns = (
            pd.to_numeric(
                trades["pnl"],
                errors="coerce"
            )
            / capital
        ).dropna()

        if len(returns) < 2:
            return 0.0

        standard_deviation = returns.std(
            ddof=1
        )

        if standard_deviation == 0:
            return 0.0

        return float(
            returns.mean()
            / standard_deviation
            * np.sqrt(len(returns))
        )

    # ==================================================
    # SORTINO RATIO
    # ==================================================

    @staticmethod
    def sortino_ratio(
        returns
    ) -> float:
        """
        Calculate Sortino Ratio.

        Parameters
        ----------
        returns : array-like
            Return series.

        Uses zero as the minimum acceptable return.

        Returns
        -------
        float
        """

        returns = pd.Series(
            returns,
            dtype="float64"
        ).dropna()

        if returns.empty:
            return 0.0

        downside_returns = returns[
            returns < 0
        ]

        if downside_returns.empty:
            return float("inf")

        downside_deviation = np.sqrt(
            np.mean(
                downside_returns ** 2
            )
        )

        if downside_deviation == 0:
            return 0.0

        return float(
            returns.mean()
            / downside_deviation
            * np.sqrt(len(returns))
        )

    # ==================================================
    # VOLATILITY
    # ==================================================

    @staticmethod
    def volatility(
        returns
    ) -> float:
        """
        Calculate standard deviation of returns.

        Returns the result as a percentage.
        """

        returns = pd.Series(
            returns,
            dtype="float64"
        ).dropna()

        if len(returns) < 2:
            return 0.0

        return float(
            returns.std(ddof=1) * 100
        )
