from dataclasses import dataclass
from datetime import datetime


@dataclass
class StrategySignal:
    """
    Represents an entry signal generated by the strategy.

    The Strategy Engine is responsible for determining
    the entry price, stop loss and target.
    """

    symbol: str

    entry_date: datetime

    entry_price: float

    sl: float

    target: float

    signal: bool = True

    def to_dict(self) -> dict:
        """
        Convert the strategy signal to a dictionary.
        """

        return {
            "symbol": self.symbol,
            "entry_date": self.entry_date,
            "entry_price": self.entry_price,
            "sl": self.sl,
            "target": self.target,
            "signal": self.signal,
        }